formatters:
  default:
    format: '[%(asctime)s] %(levelname)s in %(name)s of %(module)s : %(message)s'
handlers:
  wsgi:
    class: logging.StreamHandler
    formatter: default
    stream: ext://flask.logging.wsgi_errors_stream
  logfile:
    class: logging.FileHandler
    filename: logconfig.log
    formatter: default
root:
  handlers:
  - wsgi
  - logfile
  level: INFO
version: 1
